### ISSUE TITLE
Gap characters in sequences?

### ISSUE THREAD

**Issue by metasoarous** [s312569/clj-biosequence#30]
It seems these are currently converted to 'X' characters under the `:iupacNucleicAcids` alphabet.
Could clj-biosequence be modified to allow for traditional gap characters (`-`) to remain unchanged?

**Comment by s312569** [comment]
Yep - that makes sense. Should work in latest version (0.2.7) - just added '-' and '.' to the alphabet as gaps.

**Comment by metasoarous** [comment]
Ah; lovely. Thank you!
